import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react';
import Forecast from '../components/Forecast';
import Header from '../components/Header';
// import Image from 'next/image'


export interface Props {
  data?: any,
  zipCode?: number
}

export const Home: NextPage = ({ data }: Props) => {
  return (
    <div className='text-gray-600 bg-blue-600'>
      <Head>
        <title>Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div>
        <Forecast data={data} />
      </div>
    </div>
  )
};

export default Home;

export const getServerSideProps: GetServerSideProps = async (context) => {

  const zipCode = (
    document?.getElementById('zipCode') as HTMLInputElement
  ).value;
  console.log(zipCode)
  const apiLink = "https://api.openweathermap.org/data/2.5/weather?zip=90210,us&appid=225e9979cafa7faa49ef4c637d23e637";
  const res = await fetch(apiLink.replace('90210', zipCode))
  const data: Props = await res.json()
  // const zipCode: Props = zipCode

  if (!data) {
    return {
      notFound: true,
    }
  }

  return {
    props: { data }, // will be passed to the page component as props
  }


};
