import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react';
import Forecast from '../components/Forecast';
import Header from '../components/Header';
import { WeatherLocation } from '../model/Weather';
// import Image from 'next/image'
import { Weather } from '../model/Weather';
// import { searchLocation } from '../utils/Request';

export interface Props {
  data?: any,
  zipCode?: number,
  term?: string
}

export const Home: NextPage = ({ data }: Props) => {
  return (
    <div className='bg-red-300'>
      <Head>
        <title>Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div>
        <Forecast />
      </div>
    </div>
  )
};

export default Home;
